version: '3'

services:
  wrapper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    tty: true
  mongo:
    image: mongo
  redis:
    image: redis
  api:
    build:
      context: ../dc-wrapper-api
      dockerfile: Dockerfile